# Generated by Django 4.2.19 on 2025-03-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrawlResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('status_code', models.IntegerField()),
                ('content', models.TextField()),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('keywords', models.TextField(blank=True, null=True)),
                ('seo_suggestions', models.TextField(blank=True, null=True)),
                ('crawled_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
