# Generated by Django 4.2.19 on 2025-03-01 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoapp', '0002_crawlresult'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seoanalysis',
            name='keyword_density',
        ),
        migrations.RemoveField(
            model_name='seoanalysis',
            name='meta_description_score',
        ),
        migrations.RemoveField(
            model_name='seoanalysis',
            name='meta_title_score',
        ),
        migrations.AddField(
            model_name='seoanalysis',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoanalysis',
            name='keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoanalysis',
            name='seo_suggestions',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='seoanalysis',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
