# Generated by Django 4.2.19 on 2025-03-01 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seoapp', '0003_remove_seoanalysis_keyword_density_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='crawlresult',
            name='backlinks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='external_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='file_size',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='internal_links',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='media_files',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='page_speed_insights',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='response_time',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='suggested_keywords',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='crawlresult',
            name='word_count',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
